# Generated by Django 5.2.3 on 2025-06-27 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identifiant unique')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('cnib', models.CharField(max_length=15, verbose_name='Cnib')),
                ('key', models.CharField(max_length=10000, verbose_name='Key')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Groupe sanguin')),
                ('emergency_contact_name', models.CharField(max_length=200, verbose_name="Contact d'urgence (nom)")),
                ('emergency_contact_phone', models.CharField(max_length=20, verbose_name="Contact d'urgence (téléphone)")),
                ('critical_allergies', models.TextField(blank=True, verbose_name='Allergies critiques')),
                ('current_medications', models.TextField(blank=True, verbose_name='Médicaments actuels')),
                ('medical_conditions', models.TextField(blank=True, verbose_name='Conditions médicales')),
                ('past_surgeries', models.TextField(blank=True, verbose_name='Chirurgies passées')),
                ('medical_history', models.TextField(blank=True, verbose_name='Historique médical détaillé')),
                ('attending_physician', models.CharField(blank=True, max_length=200, verbose_name='Médecin traitant')),
                ('physician_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du médecin')),
                ('insurance_info', models.TextField(blank=True, verbose_name="Informations d'assurance")),
                ('additional_emergency_contacts', models.TextField(blank=True, verbose_name="Contacts d'urgence supplémentaires")),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='Code QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Individu',
                'verbose_name_plural': 'Individus',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('public', 'Accès public'), ('private', 'Accès privé (agent)')], max_length=20, verbose_name="Type d'accès")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Accédé par')),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='assist.individual')),
            ],
            options={
                'verbose_name': "Log d'accès",
                'verbose_name_plural': "Logs d'accès",
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent')], default='agent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
